server:
  port: 9999  # 端口号

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://mysql.wy1009.top:3306/study_prompting?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Shanghai
  data:
    redis:
      host: redis.wy1009.top
      password: Yxl5201314
      port: 16379
      database: 0
      timeout: 6000ms

jwt:
  secret: wy  # JWT 密钥
  expiration: 86400000  # 24小时过期（单位：毫秒）
